name: Django Tests Runner
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python3_8:
    name: python3.8
    runs-on: ubuntu-18.04
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: test_db
      DB_USERNAME: test_user
      DB_PASSWORD: test_pass
      DB_HOST: localhost
      DB_PORT: 5432
      RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
      RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 10
        postgresql db: test_db
        postgresql user: test_user
        postgresql password: test_pass
    - name: Setup Project
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Build Django Project
      run: |
        mkdir static
        mkdir media
        pip install -r requirements.txt
        pip install flake8
        python manage.py collectstatic --noinput
        python manage.py makemigrations --check
        python manage.py migrate
    - name: Flake8
      run: flake8 --config .flake8
    - name: Run Tests
      run: python manage.py test
